#!/usr/bin/env bash

# Set up autograder files
# cp /autograder/submission/*.py /autograder/source/
cd /autograder/source
python3 preprocess.py

python3 run_tests.py > /autograder/results/results.json

# python3 hide_outputs.py

